// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdsqznutntmfwkeyavri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kc3F6bnV0bnRtZndrZXlhdnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTI0MTMsImV4cCI6MjA1NzU4ODQxM30.foOxD-a6okT08-ZBzTPVe-zBmPMdoLvpijtOasCnDTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);